In [11]:
import numpy as np


In [27]:
trial = generateThetas()
trial

array([[ 0.00115145, -0.30047909, -0.25171197],
       [-0.18013821,  0.39467832, -0.18232426]])

In [7]:
trial1 = trial - 1
trial1

array([[-0.3329149 , -0.73937199, -0.41957249],
       [-0.46188762, -0.5507493 , -0.17523637]])

In [13]:
trial

array([[ 0.36098112,  0.38368381, -0.09505133],
       [-0.33642383,  0.13013196,  0.0945115 ]])