In [1]:
from generateFunctions import generateSamples, generateAnswer, generateThetas
from keras.utils import to_categorical
from scipy.special import softmax
import numpy as np

Using TensorFlow backend.


In [2]:
# thetas = [generateThetas()]
directions = [[0,1],[0,-1],[1,0],[-1,0]]
x,y=generateSamples(50000)
answers = generateAnswer(x,y,directions)
answers_cat = to_categorical(answers)

In [3]:
# thetas = np.array([[2,3],[2,-4],[6,2],[-3,1]])
thetas = generateThetas()

In [4]:
xy = np.column_stack((x,y))
z = np.matmul(xy, np.transpose(thetas))
# a = softmax(z)
# error = a - answer


In [5]:
answers_cat

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [6]:
delta = np.zeros(thetas.shape)
num_samples = x.shape[0]
for i in range(0, num_samples):
    point = xy[i]
    temp_a = softmax(z[i])
    temp_ans = answers_cat[i,:]
    temp_error = temp_ans - temp_a
    delta += .8*np.outer(temp_error,point)
delta = delta/num_samples

In [7]:
thetas_new = thetas + delta
thetas

array([[-0.28162215,  0.21874139],
       [-0.14249924, -0.36462538],
       [ 0.17250059, -0.10987418],
       [-0.20078648, -0.17877012]])

In [8]:
thetas_new

array([[ 0.43677189,  0.27744706],
       [ 0.09503653, -0.63167647],
       [ 0.26718779, -0.15174684],
       [-1.2514035 ,  0.07144796]])

In [9]:
z_new = np.matmul(xy, np.transpose(thetas_new))


In [12]:
old_count = 0
new_count = 0
for i in range(0,num_samples):
    if np.argmax(z[i]) == answers[i]:
        old_count += 1
    if np.argmax(z_new[i]) == answers[i]:
        new_count += 1
print(old_count/num_samples)
print(new_count/num_samples)


0.70644
0.58112


In [15]:
z[1]

array([-0.09841966,  3.93175972, -0.14168361,  2.7337574 ])

In [13]:
xy

array([[-9.73130297, -7.01291257],
       [-6.15695761, -8.37681111],
       [-8.79515602,  4.17652903],
       ...,
       [ 5.03535903,  2.30807391],
       [ 9.1685526 , -4.16700387],
       [ 9.0484088 ,  0.72628162]])