In [1]:
from generateFunctions import generateSamples, generateAnswer, generateThetas, trainOne
from keras.utils import to_categorical
from scipy.special import softmax
import numpy as np

Using TensorFlow backend.


In [2]:
directions = [[0,1],[0,-1]]
x,y=generateSamples(2000)
thetas = generateThetas()
thetas

array([[0.30239677, 0.25021331],
       [0.37421164, 0.33858109]])

In [3]:
trial = thetas.copy()
trial

array([[0.30239677, 0.25021331],
       [0.37421164, 0.33858109]])

In [4]:
delta = 0
for i in range(0,2000):
    trial += delta
    delta, z, ans, cat = trainOne(x[i],y[i],trial,directions)
    
    
    print(z)
    print(ans)
    print(cat)
    print('____')
#     print(trial)
#     print(thetas)
#     print('_____')


[[-0.47789107 -0.8397896 ]]
[1]
[[0. 1.]]
____
[[-18.66172286   9.35895534]]
[1]
[[0. 1.]]
____
[[-47.44860192  42.91458749]]
[1]
[[0. 1.]]
____
[[-30.34048439  36.1854562 ]]
[1]
[[0. 1.]]
____
[[ 51.94935245 -55.48124086]]
[0]
[[1.]]
____
[[ 3.12422137 29.47711582]]
[1]
[[0. 1.]]
____
[[22.209587   37.07759455]]
[0]
[[1.]]
____
[[30.90095719 30.18432638]]
[1]
[[0. 1.]]
____
[[41.04606768  8.69472859]]
[0]
[[1.]]
____
[[-27.22048749 -69.02859279]]
[0]
[[1.]]
____
[[-25.33172208   6.42384317]]
[1]
[[0. 1.]]
____
[[-25.65503931 -17.9791099 ]]
[1]
[[0. 1.]]
____
[[48.21946999 20.4973586 ]]
[0]
[[1.]]
____
[[47.89066931 37.72700748]]
[0]
[[1.]]
____
[[41.49523693 15.93593904]]
[0]
[[1.]]
____
[[ 98.43221622 184.91482392]]
[0]
[[1.]]
____
[[21.53502232 59.39934797]]
[0]
[[1.]]
____
[[-108.3322805   -99.29264967]]
[1]
[[0. 1.]]
____
[[-87.29849955 -45.9991244 ]]
[1]
[[0. 1.]]
____
[[127.36358924  86.83318207]]
[0]
[[1.]]
____
[[-197.19443228 -184.76275576]]
[1]
[[0. 1.]]
____
[[-11.91543235 

[[2564.78176357 2508.14954796]]
[0]
[[1.]]
____
[[1083.35193787  997.90939032]]
[0]
[[1.]]
____
[[-1511.20422412 -1519.7390309 ]]
[1]
[[0. 1.]]
____
[[-2652.60872773 -2608.47861106]]
[1]
[[0. 1.]]
____
[[-387.71142799 -301.40104463]]
[1]
[[0. 1.]]
____
[[-344.34692419 -342.58790882]]
[1]
[[0. 1.]]
____
[[-451.23843775 -420.50058482]]
[1]
[[0. 1.]]
____
[[2027.86939497 2032.71302171]]
[0]
[[1.]]
____
[[-1546.29263719 -1473.11927448]]
[1]
[[0. 1.]]
____
[[-2793.465068   -2689.84623514]]
[1]
[[0. 1.]]
____
[[328.51664529 329.25692175]]
[0]
[[1.]]
____
[[2218.46358035 2120.21476017]]
[0]
[[1.]]
____
[[2458.96810043 2390.14266984]]
[0]
[[1.]]
____
[[2015.64295828 2015.27448433]]
[0]
[[1.]]
____
[[83.1563953 88.0203731]]
[0]
[[1.]]
____
[[-1927.05515296 -1946.79411397]]
[1]
[[0. 1.]]
____
[[-1497.0874654  -1498.68867767]]
[1]
[[0. 1.]]
____
[[-2751.72697359 -2603.31689478]]
[1]
[[0. 1.]]
____
[[-2241.05129854 -2115.00914043]]
[1]
[[0. 1.]]
____
[[256.02207476 250.66947214]]
[0]
[[1.]]
____
[

[[-1876.1828463  -1813.77696886]]
[1]
[[0. 1.]]
____
[[-1719.56340105 -1667.22466544]]
[1]
[[0. 1.]]
____
[[4891.31405888 4723.88711019]]
[0]
[[1.]]
____
[[5124.8521804  5084.87941601]]
[0]
[[1.]]
____
[[-375.5456952  -439.31388711]]
[1]
[[0. 1.]]
____
[[3279.02731009 3301.39369435]]
[0]
[[1.]]
____
[[-2307.86141965 -2330.22551271]]
[1]
[[0. 1.]]
____
[[-2674.33992241 -2612.4021697 ]]
[1]
[[0. 1.]]
____
[[-5544.84321112 -5448.94054296]]
[1]
[[0. 1.]]
____
[[1733.68847339 1703.27601215]]
[0]
[[1.]]
____
[[-3537.79767016 -3499.91603583]]
[1]
[[0. 1.]]
____
[[3469.31965314 3432.28612583]]
[0]
[[1.]]
____
[[3836.68079457 3814.1970032 ]]
[0]
[[1.]]
____
[[5671.3340476  5709.97375245]]
[0]
[[1.]]
____
[[-159.33487011 -195.58863784]]
[1]
[[0. 1.]]
____
[[3707.6597438  3680.35725985]]
[0]
[[1.]]
____
[[3669.97794582 3645.28383704]]
[0]
[[1.]]
____
[[-3619.44603296 -3669.3763188 ]]
[1]
[[0. 1.]]
____
[[-507.06467001 -496.11531879]]
[1]
[[0. 1.]]
____
[[2457.1988091  2475.71825088]]
[0]
[[1.]]
_

[[5276.44528042 5201.06679979]]
[0]
[[1.]]
____
[[-3431.71467277 -3365.70046675]]
[1]
[[0. 1.]]
____
[[-2935.09478128 -2958.4540259 ]]
[1]
[[0. 1.]]
____
[[-2038.10012831 -1980.8515576 ]]
[1]
[[0. 1.]]
____
[[423.58335849 391.08436015]]
[0]
[[1.]]
____
[[-5207.49258974 -5171.14028361]]
[1]
[[0. 1.]]
____
[[2075.33291829 2083.69589913]]
[0]
[[1.]]
____
[[-6336.67537538 -6242.75831211]]
[1]
[[0. 1.]]
____
[[3051.14865709 3039.44571047]]
[0]
[[1.]]
____
[[-8182.57723105 -8073.42650891]]
[1]
[[0. 1.]]
____
[[6686.06846012 6687.59956889]]
[0]
[[1.]]
____
[[7320.39856711 7245.70185166]]
[0]
[[1.]]
____
[[-1975.81870869 -2051.59576122]]
[1]
[[0. 1.]]
____
[[1971.78609976 1958.07405078]]
[0]
[[1.]]
____
[[-7439.63531556 -7355.45752251]]
[1]
[[0. 1.]]
____
[[1781.32193126 1751.20635612]]
[0]
[[1.]]
____
[[4637.68729829 4604.17807447]]
[0]
[[1.]]
____
[[88.16296349 76.10019814]]
[0]
[[1.]]
____
[[-7815.52755219 -7827.81368288]]
[1]
[[0. 1.]]
____
[[-1290.37433656 -1252.16804391]]
[1]
[[0. 1.]]
_

[[-9302.75390702 -9195.26418879]]
[1]
[[0. 1.]]
____
[[-9160.74050097 -8848.53027612]]
[1]
[[0. 1.]]
____
[[8123.73484344 7988.88322612]]
[0]
[[1.]]
____
[[9717.35363716 9506.8197369 ]]
[0]
[[1.]]
____
[[10802.27883198 10787.10871611]]
[0]
[[1.]]
____
[[-1221.08191094 -1150.99779154]]
[1]
[[0. 1.]]
____
[[7929.05124321 7918.97483117]]
[0]
[[1.]]
____
[[-8770.17549794 -8814.60656215]]
[1]
[[0. 1.]]
____
[[5356.19346828 5329.96159898]]
[0]
[[1.]]
____
[[-7903.55880117 -8006.41980419]]
[1]
[[0. 1.]]
____
[[-4995.77411696 -4904.18578366]]
[1]
[[0. 1.]]
____
[[7924.43115404 7786.23872994]]
[0]
[[1.]]
____
[[8486.87283498 8446.02870756]]
[0]
[[1.]]
____
[[-5733.61328027 -5706.761226  ]]
[1]
[[0. 1.]]
____
[[-611.43008308 -658.96861498]]
[0]
[[1.]]
____
[[6006.25213932 5993.74660365]]
[0]
[[1.]]
____
[[-6682.91444802 -6665.09072236]]
[1]
[[0. 1.]]
____
[[-1975.65441921 -1985.38599901]]
[1]
[[0. 1.]]
____
[[-8109.14829524 -8126.6708659 ]]
[1]
[[0. 1.]]
____
[[-221.73773232 -217.64424748]]
[1]


[[1.]]
____
[[5899.931743   5938.61238534]]
[0]
[[1.]]
____
[[5888.47245936 5905.21157918]]
[0]
[[1.]]
____
[[3732.67183363 3717.35834139]]
[0]
[[1.]]
____
[[11988.67458452 12039.4334052 ]]
[0]
[[1.]]
____
[[7871.2491202  7835.95914911]]
[0]
[[1.]]
____
[[11647.22314266 11619.00541205]]
[0]
[[1.]]
____
[[-2131.83193424 -2130.86310076]]
[1]
[[0. 1.]]
____
[[7364.09130522 7389.01075047]]
[0]
[[1.]]
____
[[-10777.53162012 -10761.76422049]]
[1]
[[0. 1.]]
____
[[-6813.8341584  -6808.12735244]]
[1]
[[0. 1.]]
____
[[-3659.82218484 -3641.74379587]]
[1]
[[0. 1.]]
____
[[10653.34944362 10615.57292763]]
[0]
[[1.]]
____
[[15182.79542369 15237.8307133 ]]
[0]
[[1.]]
____
[[-1507.23802297 -1605.63144021]]
[1]
[[0. 1.]]
____
[[-12082.9370793  -12019.57676588]]
[1]
[[0. 1.]]
____
[[-14807.32765114 -14807.40093734]]
[1]
[[0. 1.]]
____
[[9355.47161745 9295.04465125]]
[0]
[[1.]]
____
[[862.35340683 952.45176569]]
[1]
[[0. 1.]]
____
[[5344.50087813 5337.14345981]]
[0]
[[1.]]
____
[[-8010.26295185 -8082.435

____
[[-13334.65974179 -13296.79613505]]
[1]
[[0. 1.]]
____
[[1633.36163159 1617.46679724]]
[0]
[[1.]]
____
[[-2601.54685957 -2591.4816082 ]]
[1]
[[0. 1.]]
____
[[6247.65504964 6237.48906238]]
[0]
[[1.]]
____
[[-14836.61910292 -14848.43350068]]
[1]
[[0. 1.]]
____
[[2722.82407299 2724.91595565]]
[0]
[[1.]]
____
[[8249.73849069 8168.29261934]]
[0]
[[1.]]
____
[[2593.63072481 2638.87242633]]
[0]
[[1.]]
____
[[-7064.28514479 -7017.7665902 ]]
[1]
[[0. 1.]]
____
[[-14512.77297852 -14409.68789889]]
[1]
[[0. 1.]]
____
[[17487.02140804 17352.47159532]]
[0]
[[1.]]
____
[[14524.84271164 14548.28441498]]
[0]
[[1.]]
____
[[-200.70367864 -199.73329575]]
[1]
[[0. 1.]]
____
[[12200.61548208 12129.34654449]]
[0]
[[1.]]
____
[[4278.28242597 4235.82160033]]
[0]
[[1.]]
____
[[-2447.69645544 -2445.01832407]]
[1]
[[0. 1.]]
____
[[-10558.30889502 -10541.08734736]]
[1]
[[0. 1.]]
____
[[-701.76927904 -700.5689142 ]]
[1]
[[0. 1.]]
____
[[-9929.65973785 -9926.59179476]]
[1]
[[0. 1.]]
____
[[-8082.10489525 -8076.

[[14445.08006368 14416.57102611]]
[0]
[[1.]]
____
[[1541.40865997 1570.21070025]]
[0]
[[1.]]
____
[[6504.14798571 6505.40437028]]
[0]
[[1.]]
____
[[-6500.06140862 -6518.52605059]]
[1]
[[0. 1.]]
____
[[-3572.1962634  -3566.26282114]]
[1]
[[0. 1.]]
____
[[16571.93989063 16405.27308556]]
[0]
[[1.]]
____
[[-9158.23891891 -9099.4096137 ]]
[1]
[[0. 1.]]
____
[[-8791.46710009 -8760.05359235]]
[1]
[[0. 1.]]
____
[[-14556.24476718 -14522.20513602]]
[1]
[[0. 1.]]
____
[[9648.08391183 9624.9060397 ]]
[0]
[[1.]]
____
[[15106.0098364  15089.04399559]]
[0]
[[1.]]
____
[[7045.73508064 7086.03627735]]
[0]
[[1.]]
____
[[10323.71903431 10331.79636444]]
[0]
[[1.]]
____
[[12506.51650736 12488.12372649]]
[0]
[[1.]]
____
[[-11761.49631087 -11776.17504396]]
[1]
[[0. 1.]]
____
[[9418.72900133 9371.32422101]]
[0]
[[1.]]
____
[[8906.2839318  8825.06614545]]
[0]
[[1.]]
____
[[10014.51960053  9986.23613427]]
[0]
[[1.]]
____
[[-13453.81404609 -13508.97683666]]
[1]
[[0. 1.]]
____
[[-2752.86504358 -2744.98516438]]
[

[[21440.59917937 21329.20206074]]
[0]
[[1.]]
____
[[-16130.83882317 -16082.04798838]]
[1]
[[0. 1.]]
____
[[-9409.94208099 -9468.22327373]]
[1]
[[0. 1.]]
____
[[-4494.76295433 -4473.71852315]]
[1]
[[0. 1.]]
____
[[-14565.35613964 -14441.66257692]]
[1]
[[0. 1.]]
____
[[10330.12040785 10241.33705008]]
[0]
[[1.]]
____
[[19298.7639353  19211.21824009]]
[0]
[[1.]]
____
[[-16800.35810055 -16797.71794919]]
[1]
[[0. 1.]]
____
[[-22893.98563933 -22879.36773573]]
[1]
[[0. 1.]]
____
[[21419.06844911 21371.51187245]]
[0]
[[1.]]
____
[[17411.61219215 17435.69813881]]
[0]
[[1.]]
____
[[22417.60338732 22395.20893447]]
[0]
[[1.]]
____
[[498.4449372  537.01963292]]
[0]
[[1.]]
____
[[-7824.075532   -7833.96507048]]
[1]
[[0. 1.]]
____
[[-1655.4478095  -1489.07946697]]
[1]
[[0. 1.]]
____
[[-24843.76074809 -24812.42826889]]
[1]
[[0. 1.]]
____
[[-1565.58188961 -1712.90102777]]
[1]
[[0. 1.]]
____
[[-9650.62956446 -9628.03238199]]
[1]
[[0. 1.]]
____
[[17315.8715754  17323.62012833]]
[0]
[[1.]]
____
[[12730.349

In [5]:
trial

array([[-117.96233273, 2634.29672697],
       [-114.20571663, 2632.57574924]])

In [6]:
thetas

array([[0.30239677, 0.25021331],
       [0.37421164, 0.33858109]])