In [1]:
from generateFunctions import generateSamples, generateAnswer, generateThetas, trainOne
from scipy.special import softmax
import numpy as np

Using TensorFlow backend.


In [2]:
directions = [[0,1],[0,-1]]
sampleSize = 100
x,y=generateSamples(sampleSize)
thetas = generateThetas()
thetas

array([[ 0.10137731,  0.07273256],
       [-0.39776646, -0.05142376]])

In [3]:
trial = thetas.copy()

In [4]:
for i in range(0,5):
    ans = generateAnswer([x[i]],[y[i]],directions)
    print(x[i])
    print(y[i])
    print(ans)
    print('_____')

-0.34520360641503395
-0.2808743026247919
[[0 1]]
_____
0.42413611165539383
0.36142106079939357
[[1 0]]
_____
-0.7066603012528596
0.21061033728662712
[[1 0]]
_____
-0.5536131761815359
0.11904781137219564
[[1 0]]
_____
-0.38553738967951817
0.08920422021660107
[[1 0]]
_____


In [5]:
delta = 0
for i in range(0,sampleSize):
    trial += delta
    delta, z, ans = trainOne(x[i],y[i],trial,directions)
    
    
#     print(z)
#     print(ans)
# #     print(cat)
#     print('____')
    print(trial)
    print(thetas)
    print(delta)
    print('_____')


[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[ 0.15478579  0.12594118]
 [-0.15478579 -0.12594118]]
_____
[[ 0.2561631   0.19867374]
 [-0.55255225 -0.17736494]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[ 0.16223574  0.13824669]
 [-0.16223574 -0.13824669]]
_____
[[ 0.41839884  0.33692043]
 [-0.71478799 -0.31561163]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[-0.46640435  0.13900537]
 [ 0.46640435 -0.13900537]]
_____
[[-0.04800551  0.4759258 ]
 [-0.24838364 -0.45461701]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[-0.27682775  0.05952846]
 [ 0.27682775 -0.05952846]]
_____
[[-0.32483326  0.53545426]
 [ 0.02844411 -0.51414546]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[-0.17071364  0.03949909]
 [ 0.17071364 -0.03949909]]
_____
[[-0.4955469   0.57495335]
 [ 0.19915775 -0.55364456]]
[[ 0.10137731  0.07273256]
 [-0.39776646 -0.05142376]]
[[-0.21478465  0.05929671]
 [ 0.214

In [6]:
trial

array([[ 0.11357872,  4.09781836],
       [-0.40996787, -4.07650957]])

In [7]:
thetas

array([[ 0.10137731,  0.07273256],
       [-0.39776646, -0.05142376]])

In [8]:
delta

array([[-0.01010068,  0.01743287],
       [ 0.01010068, -0.01743287]])